### ISSUE TITLE
Conflicting with `'Fabric Language Kotlin' (fabric-language-kotlin) 1.10.13+kotlin.1.9.20`

### ISSUE THREAD

**Issue by SettingDust** [FrozenBlock/Configurable-Everything#15]
```
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabric Language Kotlin' (fabric-language-kotlin) 1.10.13+kotlin.1.9.20 with version 1.10.10+kotlin.1.9.10.
More details:
	 - Mod 'Configurable Everything' (configurable_everything) 1.0.3-Fabric+1.20.1 requires version 1.10.10+kotlin.1.9.10 of mod 'Fabric Language Kotlin' (fabric-language-kotlin), but only the wrong version is present: 1.10.13+kotlin.1.9.20!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.24.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.24.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[?:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[?:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[?:?]
```

**Comment by EthanRStokes** [comment]
Fixed in upcoming 1.0.4 release
(By updating to Kotlin 1.9.20 and setting the dependency to use `>=`)
